name: CI
on: ["push"]
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2

  
      - uses: actions/setup-go@v3
        with:
          go-version: '^1.13.8'

      - name: Create go.mod file
        run: go mod init github.com/stem-discord/potd-bot/stav

      - name: Get discord
        run: go get github.com/bwmarrin/discordgo 

      - name: Get godotenv
        run: go get github.com/joho/godotenv
      
      - name: Get cron.v2  
        run: go get gopkg.in/robfig/cron.v2

      - name: Check if build works
        run: go build ./stav/main.go
      
  sandbox-deploy:
    needs: build
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    steps:
      - name: Check out Git repository
        uses: actions/checkout@v2
        with:
        # My poor raspberry pi needs to survive. No more disk stuff
         clean: false

      - run: " > .env"
      - run: |
          echo "DISCORD_BOT_ID=960764870490476554
          POTD_ROLE_ID=976351806974201866
          POTD_CHANNEL_ID=976351498806099971" >> .env

      - run: echo "DISCORD_BOT_TOKEN=${{ secrets.DISCORD_BOT_TOKEN }}" >> .env

      - run: pm2 restart potd-bot

      # - name: Discord notification
      #   uses: tsickert/discord-webhook@v4.0.0
      #   if: success() || failure()
      #   with:
      #     content: '{{ EVENT_PAYLOAD.repository.full_name }} deploy to sandbox {{["FAILED", "SUCCEEDED"][success()]}} <@341446613056880641>'
      #     webhook-url: ${{ secrets.DISCORD_CD_UPDATE_WEBHOOK }}
